---
title: "Introduction to Grapher"
output: html_notebook
---

```{r}
library("igraph")
library("grapher")
n_nodes <- 10L
G <- igraph::sample_grg(n_nodes, radius = 0.1)

# grapher(G)
label_xy <- data.frame(label = 1:2, x = c(0.05, 0.95), y = c(0.5, 0.5))
node_labels <- c(rep(1, n_nodes/2), rep(2, n_nodes/2))

grapher(G) %>% 
  updateNodeColor(color = c(rep(rgb(1, 0, 0, 0.5), n_nodes/2), rep(rgb(0, 1, 0, 0.5), n_nodes/2))) %>% 
  splitByLabel(node_labels = node_labels, label_xy = label_xy) %>% 
  groupSingletons()

edge_colors <- apply(igraph::as_edgelist(G), 1, function(edge){ 
  if (edge[1] <= 25 && edge[2] <= 25){ rgb(1, 0, 0) } 
  else if (edge[1] > 25 && edge[2] > 25){ rgb(0, 1, 0) } 
  else { rgb(0, 0, 1) }
})
grapher(adjm) %>% 
  updateNodeColor(color = c(rep(rgb(1, 0, 0), n_nodes/2), rep(rgb(0, 1, 0), n_nodes/2))) %>% 
  updateEdgeColor(color = edge_colors) %>% 
  grapher:::logNetwork()


el <- igraph::as_edgelist(G) 
edge_types <- cbind(node_labels[el[, 1]], node_labels[el[, 2]])
internal_edges <- which(apply(edge_types, 1, function(e) e[1] == e[2]))
cross_edges <- which(apply(edge_types, 1, function(e) e[1] != e[2]))

grapher(G) %>% 
    updateNodeColor(color = c(rep(rgb(1, 0, 0, 0.5), n_nodes/2), rep(rgb(0, 1, 0, 0.5), n_nodes/2))) %>% 
    splitByLabel(node_labels = c(rep(1, n_nodes/2), rep(2, n_nodes/2)), label_xy = label_xy) %>% 
    removeEdges(v1 = el[cross_edges, 1], v2 = el[cross_edges, 2]) %>% 
    removeEdges(v1 = el[internal_edges, 1], v2 = el[internal_edges, 2]) %>% 
    addEdges(v1 = el[1, 1], v2 = el[1, 2], color = rgb(1, 0, 0))


grapher(G) %>% 
  updateNodeColor(color = c(rep(rgb(1, 0, 0, 0.5), n_nodes/2), rep(rgb(0, 1, 0, 0.5), n_nodes/2))) %>% 
  splitByLabel(node_labels = c(rep(1, n_nodes/2), rep(2, n_nodes/2)), label_xy = label_xy) %>% 
  addEdges(v1 = el[cross_edges, 1], v2 = el[cross_edges, 2], color = rgb(0, 0, 1))
  removeEdges(v1 = el[cross_edges, 1], v2 = el[cross_edges, 2]) %>% 
  removeEdges(v1 = el[internal_edges, 1], v2 = el[internal_edges, 2]) %>% 
  addEdges(v1 = el[cross_edges, 1], v2 = el[cross_edges, 2], color = rgb(0, 0, 1)) %>% 
  addEdges(v1 = el[1:5, 1], v2 = el[1:5, 2], color = rgb(0, 0, 1)) %>% 
  addEdges(v1 = el[6:10, 1], v2 = el[6:10, 2], color = rgb(0, 1, 0))
  grapher:::logNetwork()


net_config <-  grapher::getDefaultJsonConfig(G)
new_config <- net_config
new_config$nodes <- new_config$nodes[1,]
new_config$nodes$color <- rgb(0, 0, 1)
new_config$links <- data.frame(from = 1, to = 2, color = rgb(0, 0, 1))
grapher(net_config) %>% 
  grapher::updateNodes(node_ids = c(1L), net_config = new_config) %>% 
  grapher:::logNetwork()
  updateNodeColor(color = c(rep(rgb(1, 0, 0, 0.5), n_nodes/2), rep(rgb(0, 1, 0, 0.5), n_nodes/2))) %>% 
  splitByLabel(node_labels = node_labels, label_xy = label_xy) %>% 
  groupSingletons()
```

## Using Mapper

```{r}
## Generate noisy points around the perimeter of a circle 
n <- 150
t <- 2*pi*runif(n)
u <- runif(n, min = 2, max = 2.1) + runif(n,  min = 2, max = 2.1)
r <- ifelse(u > 1, 2 - u, u) 
circ <- cbind(r*cos(t), r*sin(t))

## Define filter values equal to the distance from each point to the left-most point in the circle 
f_x <- abs(circ[, 1] - circ[which.min(circ[, 1]), 1])

## Mapper settings
input_params <- list(X = circ, filter_values = f_x)
cover_params <- list(cover_type = "restrained rectangular", number_intervals = 5L, overlap = 0.20)

## Different representations
m1 <- do.call(Mapper::mapper, c(input_params, cover_params, return_reference = TRUE))
m2 <- do.call(Mapper::mapper, c(input_params, cover_params, return_reference = FALSE))
```

```{r}
grapher(m1)
```

Two networks
```{r}
n_nodes <- 10L
G1 <- igraph::sample_grg(n_nodes, radius = 0.2)
G2 <- igraph::sample_grg(n_nodes, radius = 0.2)

G <- igraph::disjoint_union(G1, G2)
wut <- 

map <- function(x, values){
  keys <- names(values)
  idx <- match(x, as(keys, class(x)))
  as.vector(unlist(values))[idx]
}

net_id <- c(rep(1L, n_nodes), rep(2L, n_nodes))

G_star <- igraph::add_edges(G, edges = c(5, 15))
grapher::grapher(as.matrix(igraph::as_adjacency_matrix(G_star))) %>% 
  updateNodeColor(color = map(net_id, values)) %>% 
  splitByLabel(node_labels = net_id, label_xy = data.frame(label = 1:2, x = c(0, 1), y = c(0.5, 0.5))) %>% 
  

```
